### ISSUE TITLE
How download release?

### ISSUE THREAD

**Issue by jenokizm** [rainers/cv2pdb#15]
why the folder https://github.com/rainers/cv2pdb/releases is empty? I do not have time to do the assembly

**Comment by rainers** [comment]
Binary releases are available with Visual D: https://github.com/dlang/visuald/releases

**Comment by rainers** [comment]
cv2pdb.exe can also be downloaded from the artifacts of the latest successful Visual D build on AppVeyor now. See the Releases tab.
