### ISSUE TITLE
PDB to DWARF

### ISSUE THREAD

**Issue by dm1seven** [rainers/cv2pdb#18]
Hi,
What about the PDB to DWARF conversion? This would be extremely useful if you want to debug PDB files in Eclipse CDT.  See here: https://mingw-w64.org/doku.php/contribute#debug_infos

**Comment by rainers** [comment]
Sorry, but a converter from PDB to DWARF is out of the scope of this project.

BTW: Reading PDB files is very different and well documented, check the DIA SDK.

**Comment by dm1seven** [comment]
Thanks for your answer. I had no idea about DIA SDK.
