### ISSUE TITLE
RSDS files not parsed.

### ISSUE THREAD

**Issue by ruslanu** [rainers/cv2pdb#20]
When trying to parse RSDS signature files, program reports "no codeview debug entries found". It's because only NB09/NB11 signatures supported. Function PEImage::initCVPtr() should return false and try DWARF segments if signature not supported:
    if (memcmp(sig->Signature, "NB09", 4) != 0 && memcmp(sig->Signature, "NB11", 4) != 0)
    		{
    			// return setError("can only handle debug info of type NB09 and NB11");
    			dirHeader = 0;
    			dirEntry = 0;
    			**return false**;
    		}

**Comment by rainers** [comment]
Thanks for the report. What program created a binary with both CV signature and DWARF?

Not sure why it was returning success, but it's been that way since the first commit. I changed it in master, next build will contain it.
