### ISSUE TITLE
cv2pdb returns error code 127 when handling a fairly large DLL file

### ISSUE THREAD

**Issue by wyldckat** [rainers/cv2pdb#21]
We started to use `cv2pdb` in the project [blueCFD-Core](http://bluecfd.github.io/Core/) a few days ago and it works very well... with only one exception, hence this report. 

The build option `-gdwarf` has been used with `g++` with over 300 different binaries (108 DLL and 228 EXE) and `cv2pdb` worked without problems on all of them, except for one.

This one is an 829 MB DLL file which results in `cv2pdb` to give an error code of 127, after what it seems to have generated a partial PDB file of 2.9 MB. Download link on DropBox for the file `cv2pdb.bug.libfiniteVolume.7z` (94 MB), which provides the file `libfiniteVolume.dll` that triggers this issue, is as follows: https://www.dropbox.com/s/68xaxtmmahxkqs1/cv2pdb.bug.libfiniteVolume.7z?dl=0

Currently our workaround has been to simply ignore the error and strip the debug data from the DLL with `strip --strip-unneeded`, (edit) which results in a DLL file with only 23 MB.

We are using:
* MSys2 software stack with the MinGW64 installation (last updated on the 29th of September, 2017), which comes with GCC 7.2.0.
* `cv2pdb` which was downloaded from the AppVeyor link provided [here](https://github.com/rainers/cv2pdb/releases/tag/v0.38), on the 6th of October 2017.

I haven't managed to get the time needed to build `cv2pdb` myself from source code, therefore I haven't tried debugging it.

**Comment by rainers** [comment]
It seems this is just an out-of-memory problem due to the size of the DLL. cv2pdb currently expects it can hold 2 copies of the image in memory. With /LARGEADDRESSAWARE enabled, the DLL is processed without error. For even larger DLLs you will have to compile cv2pdb as a 64-bit executable (an appropriate configuration exists).

The new AppVeyor build should include this change.

**Comment by wyldckat** [comment]
Excellent! Many thanks for the quick reply and fix!

I've tested this just now and it's working perfectly with the latest build from AppVeyor.

I'll make a note regarding the need to build `cv2pdb` in 64-bit, if we start getting DLL files larger than 1GB.
