### ISSUE TITLE
64-bit windows binary on AppVeyor

### ISSUE THREAD

**Issue by leavittx** [rainers/cv2pdb#29]
There is 32-bit binary provided here: https://github.com/rainers/cv2pdb/releases/tag/v0.38
Shouldn't there be a 64-bit version as well?
Or is that possible to use 32-bit one to work with 64-bit exe/dll?

**Comment by rainers** [comment]
You can use the 32-bit version to convert 64-bit executables, there's just a lower limit on the maximum size (about 1GB IIRC).

**Comment by dscho** [comment]
@leavittx there are now binaries being built as part of the GitHub workflow and offered as build artifacts (called "bin"). See for example https://github.com/rainers/cv2pdb/actions/runs/1563947603. Does that address this ticket?

**Comment by olback** [comment]
@dscho Sadly, artifacts expire after a few weeks.

**Comment by dscho** [comment]
@olback good thing that you can push the branch to your fork, then, to build the artifacts yourself :grin:

**Comment by rainers** [comment]
There are also permanent releases available here: https://github.com/rainers/cv2pdb/releases
I have added a 64-bit binary to the latest release.
