### ISSUE TITLE
Get rid of MSPDB*.dll

### ISSUE THREAD

**Issue by KOLANICH** [rainers/cv2pdb#32]
These dlls are proprietary and parts of Visual Studio.

<details>
<summary>offtop</summary>
If you are curious why I need PDB without VS, this is because I wanna try to use x64dbg, and it doesn't understand dwarf and the official recomendation is to create pdb using this tool.
</details>

**Comment by rainers** [comment]
Sorry, but this is way beyond the scope of this project.

LLVM's linker LLD can write PDB files without the MS DLLs, and there are also DWARF readers in their source tree, so you might be able to combine these.
