### ISSUE TITLE
Quick build from command line with latest installed version of Visual Studio

### ISSUE THREAD

**Issue by vmurashev** [rainers/cv2pdb#36]
Hello folks,
Would you accept a small one-file contribution which let us build cv2pdb binary from command line with latest installed version of Visual Studio ?

If yes, then build process would look like:
native bitness: ```python -m minibuild```
win32: ```python -m minibuild --model win32```
win64: ```python -m minibuild --model win64```

On my machine with VS-2017 installed target binaries are here:
- bin\output\exe\msvs2017-win32\release\cv2pdb.exe
- bin\output\exe\msvs2017-win64\release\cv2pdb.exe

[minibuild](https://minibuild.github.io/minibuild/) itself is a pure python package,
so as a prerequisite for build Python-2.7 or Python-3.x is required.
And then `minibuild` package is supposed to be installed by pip: `python -m pip install minibuild`

If no, then just close this issue.

**Comment by rainers** [comment]
Sorry for the late reply, I've been on vacation. Thanks for considering to contribute to cv2pdb.

I don't think adding another way to build cv2pdb adds much, though. You can build it from the command line with `msbuild cv2pdb.vcxproj` with appropriate options for configuration and tool chain.
