### ISSUE TITLE
.dbg for a 64 bit executable

### ISSUE THREAD

**Issue by tim-lebedkov** [rainers/cv2pdb#40]
I converted a .dbg file for a 64 bit executable to .pdb. The .pdb is 32 bit (DBI-Stream Machine = 332).

I guess this is why AMD uProf does not load the .pdb file. Does cv2pdb always create 32 bit .pdb from a .dbg file? Can a .dbg file be 64 bit? Could you please add an option to force the creation of a 64 bit .pdb?

**Comment by tim-lebedkov** [comment]
BTW, thank you very much for this software!

**Comment by tim-lebedkov** [comment]
The .dbg file is 64 bit. The values at the offset 4 are 0x64 0x86 (as in file).

**Comment by rainers** [comment]
I don't know much abiout DBG files, support for these has been added by @AlexWhiter. Maybe he can comment on 64-bit versions? Maybe only this line needs to be adapted: https://github.com/rainers/cv2pdb/blob/master/src/cv2pdb.cpp#L71

**Comment by tim-lebedkov** [comment]
It seems hdr64 is never set in https://github.com/rainers/cv2pdb/blob/master/src/PEImage.cpp#L309 so that isX64() returns false. Would any of have time to look into this?

**Comment by AlexWhiter** [comment]
@tim-lebedkov 
Could you please try to change DbiStreamHeader.Machine value in your PDB manually to check if uProf would load it?

**Comment by rainers** [comment]
The machine type should now be set in the PDB as found in the DBG.
