### ISSUE TITLE
cv2pdb crashes if mspdb*.dll cannot be loaded from path

### ISSUE THREAD

**Issue by AlexWhiter** [rainers/cv2pdb#41]
In the following conditions:
1. Visual Studio 2013 or previous version is installed.
2. mspdb.dll version cannot be loaded from %path%.
3. One of mspdb.dll is available in MSVC installation directory.
release version of cv2pdb crashes when trying to load mspdb140 via Studio SDK API.
The exception occurs in https://github.com/rainers/cv2pdb/blob/master/src/mspdb.cpp#L99

Problem is ISetupConfiguration cannot be instantiated, result code is REGDB_E_CLASSNOTREG, so query is NULL, and query->EnumInstances leads to access violation.

**Comment by rainers** [comment]
Added the null check.
