### ISSUE TITLE
Extract from dll

### ISSUE THREAD

**Issue by Karaulov** [rainers/cv2pdb#42]
not works!

[Game.zip](https://github.com/rainers/cv2pdb/files/2698155/Game.zip)

**Comment by rainers** [comment]
> 
> 
> [Game.zip](https://github.com/rainers/cv2pdb/files/2698155/Game.zip)

This DLL is either already converted, or the original DLL and the linker already produced a pdb file. Did you mean to attach another file?

**Comment by Karaulov** [comment]
This DLL contain some debug information(dwarf2??). But cv2pdb don't see this info.  This is fatal error?(((

**Comment by rainers** [comment]
The debug directory links to section with a pdb file reference.
I don't see any DWARF info (usually in other image sections), also MinGWs objdump doesn't show anything with `objdump -W Game.dll`.
