### ISSUE TITLE
Uninitialized DWARF_LineState.last_addr 

### ISSUE THREAD

**Issue by WiwilaJuicebox** [rainers/cv2pdb#43]
When the first state machine state in dwarf is a "reuse previous address" (adr == 0 in code), state.address become the value of state.last_addr which is not initialized to 0 and then corrupt every following reading (in my case Oxcccccccc). See code in dwarflines.cpp line ~247
To fix this I initialized last_addr to 0 which should be the default value if no address hasn't been set before in dwarf

**Comment by rainers** [comment]
Thanks for the report. I added the initialization to the constructor of `DWARF_LineState`.
