### ISSUE TITLE
Debugging Unions

### ISSUE THREAD

**Issue by optomux** [rainers/cv2pdb#47]
Works great with MSVC debugger so far. However there is one issue.
MSVC debugger shows unions as well, however with this the 7th field is missing.

```
struct value {
    HKEY hKey;
    LPCSTR lpSubKey;
    LPCSTR lpKeyName;
    DWORD dwFlags;
    DWORD dwType;
    DWORD dwSize;
    union
    {
      DWORD vDWORD;
      DWORD vQWORD;
      LPCSTR vSZ;
    };
};

const value values[] = { }; // fill with some values.
```

**Comment by rainers** [comment]
What compiler are you using?

**Comment by optomux** [comment]
GCC 8.

**Comment by rainers** [comment]
The unnamed union is causing trouble, `union  { /*..*/ } u;` should be fine. You'll have to add it to accesses, too, though.

**Comment by optomux** [comment]
So some macro for debugging then?

**Comment by rainers** [comment]
This commit should help: https://github.com/rainers/cv2pdb/commit/14641495119635e26aabad1dbccc79a6dd1fc94c

If you don't compile cv2pdb yourself, you'll have to wait for the next build of the Visual D project...

**Comment by rainers** [comment]
Release link updated
