### ISSUE TITLE
Crash on MinGW-w64 GCC 4.6.3 32-bit generated executable

### ISSUE THREAD

**Issue by net147** [rainers/cv2pdb#5]
I get a crash running "cv2pdb -C DebugTest.exe" with latest git master.
Download: https://www.dropbox.com/s/xxj1m9j9hg54ceo/DebugTest.exe

It works if I use cv2pdb 0.31.

**Comment by rainers** [comment]
Please try new master...

**Comment by net147** [comment]
Works now. Thanks.
