### ISSUE TITLE
Visual Studio still says "Source Not Available"

### ISSUE THREAD

**Issue by Daniel15** [rainers/cv2pdb#50]
Hi! I'm trying to use your app to get debugging symbols for the [GPGME](https://www.gnupg.org/software/gpgme/index.html) C library, so I can debug some issues with my usage of it from C#.

I've compiled my own version of `libgpgme-11.dll` with debug symbols intact, and have used `cv2pdb` to generate a PDB. Visual Studio says:
> Loaded 'C:\Program Files (x86)\GnuPG\bin\libgpgme-11.dll'. Symbols loaded.

Which makes me think that it has found the PDB file.

However, It still says:
> Source Not Available
> Source information is missing from the debug information for this module

when I try to debug the library:
![image](https://user-images.githubusercontent.com/91933/52242132-8b596400-288a-11e9-9c5b-069c091307b6.png)

Do you know what could be causing it?

I've attached the original DLL, DLL output by cv2pdb, and the PDB file here: [libgpgme-11.zip](https://github.com/rainers/cv2pdb/files/2830052/libgpgme-11.zip)

**Comment by rainers** [comment]
There is only debug information for the mingw runtime in the original DLL. You can check by dumping the output of `objdump.exe -W libgpgme-11-original.dll` and searching for `DW_TAG_compile_unit`.

I guess something went wrong when building a debug version of that DLL.

**Comment by Daniel15** [comment]
Thanks for your reply, @rainers! I'm following up on the GPG mailing list to determine what's up: https://lists.gnupg.org/pipermail/gnupg-devel/2019-February/034189.html

I guess this is not a cv2pdb issue so I'm going to close this, but I'll reopen it if I still have issues once I figure out how to get the proper symbols in the DLL.

**Comment by Daniel15** [comment]
I worked this out. The build process for libgpgme didn't properly pass through the `CFLAGS` and `CXXFLAGS` I specified. I manually modified the Makefile and added `-gdwarf -O0`, now the debug symbols are working:

![](https://d.sb/2019/02/devenv_05-23.01.28.png)

Thank you for the useful tool!
