### ISSUE TITLE
Invalid entrys in generated pdb

### ISSUE THREAD

**Issue by nevilad** [rainers/cv2pdb#55]
I've generated a pdb from an exe with debugging info and try to debug it with windbg, but no locals are shown. Running cvdump on this pdb shows a lot errors, examples are:
Error on OpenTpi: 'Invalid file format' (11)
list[31] = LF_MEMBER, none, type = 0x116E, offset = Invalid Numeric Leaf
Size = Invalid Numeric Leaf, class name = TCGContext, UDT(0x0000137d)
[qemu-system-i386_orig.zip](https://github.com/rainers/cv2pdb/files/3406687/qemu-system-i386_orig.zip)

**Comment by rainers** [comment]
happened for aggregates larger than 32kB. Fix is committed.

**Comment by nevilad** [comment]
The
Error on OpenTpi: 'Invalid file format' (11)
is still there, other invalid entrys are gone.

**Comment by rainers** [comment]
I don't see that error. Do you use this version of cvdump? https://github.com/Microsoft/microsoft-pdb/tree/master/cvdump

**Comment by nevilad** [comment]
Yes, this version. Running it and watching loaded dlls does not show mspdb or other specific system dlls. I will try it on a different machine.

**Comment by nevilad** [comment]
The error is on a host with mspdb80, using mspdb14 generates correct pdbs. I tried to run cv2pdb on a host with windbg installed and got "PDB helper not found error". Searching by name didn't find mspdb dlls on this host, so these are not installed with windbg.
Is it possible to move mspdb dlls on a different host? When not, users should install the latest versions of VS to use cv2pdb.

**Comment by rainers** [comment]
> The error is on a host with mspdb80,

Thanks for figuring this out. That is a pretty old version, not sure it's worth digging into that.

> Is it possible to move mspdb dlls on a different host?

I think it is, though I haven't tried in a while. There are a couple of additional files needed but that also depends on the version (e.g. mspdbsrv.exe, msobj*.dll IIRC).

**Comment by nevilad** [comment]
I've copied msobj140.dll, mspdb140.dll,mspdbcore.dll, mspdbsrv.exe and vcruntime140.dll from the host with VS17 to a host with VS2008 Express, ran cv2pdb and it used mspdb140, so there is a solution to make cv2pdb portable.

**Comment by gwald** [comment]
VS 2019 needed tbbmalloc.dll but also worked.
