### ISSUE TITLE
Strip DWARF debug information from executable

### ISSUE THREAD

**Issue by net147** [rainers/cv2pdb#6]
It would be nice if it were possible to strip the DWARF debugging information from the executable while maintaining compatibility with the generated PDB.

**Comment by net147** [comment]
Alternatively, could we have an option to write a .debug codeview section to an executable for an existing .pdb so something like the following could be done using cv2pdb and MinGW binutils?
```
cv2pdb -C DebugTest.exe
strip DebugTest.exe
cv2pdb -pDebugTest.pdb DebugTest.exe
```

**Comment by rainers** [comment]
If the debug sections are at the end of the section list, it should not be too difficult to remove them. This is also what's done with CV4 debug sections.

**Comment by net147** [comment]
Last I checked they are.

**Comment by rainers** [comment]
I implemented always stripping the DWARF sections (if they are at the end). Please try latest git HEAD.

**Comment by net147** [comment]
It works. Thanks.
