### ISSUE TITLE
MINGW32 usage

### ISSUE THREAD

**Issue by atversky** [rainers/cv2pdb#61]
Any advise on usage on MINGW32 produced exe?
Used in follow way: cv2pdb Orig.exe New.exe New.pdb

Getting error: cannot add line number info to module
New.pdb is created - cannot validate if correct
New.exe - is not present

**Comment by rainers** [comment]
The error message indicates that the conversion process is aborted during line number emission, with the MS pdb writer rejecting some information. The resulting pdb is unlikely to be useful. Maybe the exe has some broken information or it uses some newer unsupported DWARF extensions.

If you can provide an example binary I might be able to figure out more.

**Comment by atversky** [comment]
Loaded ZIPPED exe into GDrive shared folder:
https://drive.google.com/drive/folders/1o8cv0pGx-SiBMzj_Jxvnux1ss2o_fzxh?usp=sharing

**Comment by rainers** [comment]
Sorry, but it seems the folder is empty.

**Comment by atversky** [comment]
You should login with you Google credentials.
Where to upload the file? - it is 72MB.

**Comment by atversky** [comment]
Fork your repository. Pushed exe to Github.
Try download from this location: https://github.com/atversky/cv2pdb/blob/master/test/artifacts/suricata.exe

**Comment by rainers** [comment]
As suspected the file uses DWARF4 line number infos. I have pushed a version that succeeds translating the debug info. Please give it a try.

**Comment by atversky** [comment]
Confirm, resolved.
Thanks!

________________________________
