### ISSUE TITLE
Hang when vswhere produces no output

### ISSUE THREAD

**Issue by LordAro** [rainers/cv2pdb#72]
I'm not entirely sure how, but I've ended up with the situation where I have `vswhere.exe`, but no actual Visual Studio install (Just MSBuild/build tools, i think?)

Obviously I'm in the wrong for not having a working VS install, but I don't think the tool should hang either :)

As best as I can tell, it's hanging on the ReadFile at:

https://github.com/rainers/cv2pdb/blob/c99df6c1597de7cfb174ab05beb3949a63a4b8c9/src/mspdb.cpp#L204-L210

due to `read` being a pipe, and `vswhere` producing no output?

![image](https://user-images.githubusercontent.com/4007992/157119077-14381979-97aa-4ca6-9073-3e6e655101b7.png)

Procmon shows that's what it did last before hanging forever, at any rate (it was still running when this screenshot was taken):

![image](https://user-images.githubusercontent.com/4007992/157118737-565beedd-9737-4266-9418-a07d6ab6ea2e.png)

**Comment by rainers** [comment]
Fixed in https://github.com/rainers/cv2pdb/releases/tag/v0.51
