### ISSUE TITLE
produces empty pdb for wined3d

### ISSUE THREAD

**Issue by Trass3r** [rainers/cv2pdb#75]
Tested the tool on https://github.com/Trass3r/wined3d4win/suites/6333289962/artifacts/227925899.
It produces a working pdb for ddraw.dll but only a small 11KB one for wined3d.dll with mostly zeros inside.

**Comment by rainers** [comment]
It seems the conversion stumbles over the compilation unit hlsl.yy.c (some exception output when the pdb is closed). I suspect this is a generated file with a large parser function. Needs some more investigation...

**Comment by Trass3r** [comment]
Yeah comes from https://github.com/wine-mirror/wine/blob/master/libs/vkd3d/libs/vkd3d-shader/hlsl.y.
Not important to get that one right.

**Comment by rainers** [comment]
Finally figured this one out: the problem is caused by struct debug information that exceeds 64 kB.

**Comment by Trass3r** [comment]
Thanks seems to work now.
