### ISSUE TITLE
Invalid form=11 for directory index lineHdrOffs=7ded41

### ISSUE THREAD

**Issue by petitg1987** [rainers/cv2pdb#76]
I have a binary built on MinGw/Msys with g++ v11.2.0 and I've got the following error when I try to use cv2pdb on it:

```
$ ./cv2pdb.exe photonEngineer.exe
interpretDWARFLines:386: ERROR: invalid form=11 for directory index lineHdrOffs=7ded41
C:\msys64\home\greg\photonEngineer.pdb: cannot add line number info to module
```

Here is the executable file: https://drive.google.com/file/d/1BsmJmojMkkdN95nZ4-JU5uX6KikgFbXv/view?usp=sharing 

Any idea on the cause of the error ? I tried with a hello world binary and it works correctly (no error).

**Comment by rainers** [comment]
> interpretDWARFLines:386: ERROR: invalid form=11 for directory index lineHdrOffs=7ded41

If parsing up to that point was correct, it means that there is an invalid entry in the debug line number infos. This is part of the DWARF5 debug info format, so maybe switching to an earlier version might help.



> Here is the executable file: https://drive.google.com/file/d/1BsmJmojMkkdN95nZ4-JU5uX6KikgFbXv/view?usp=sharing

The file is behind a login and additional security checks, can you make it more easily downloadable?

**Comment by petitg1987** [comment]
Thank you for your answer. 
I will try soon to build the application with DWARF4 and check if it works.
Is cv2pdb supposed to work with DWARD5 ?

Here is a link to download the file without login request: https://cv2pdb.s3.eu-central-1.amazonaws.com/photonEngineer.exe

**Comment by rainers** [comment]
DWARF5 support was recently added by some contributors, so I'm not too familiar with it. According to the spec, some data formats were not supported, https://github.com/rainers/cv2pdb/commit/f390ed4c0aef0f0acd3f880c82564558bc2e0786 seems to fix that.

**Comment by petitg1987** [comment]
Fix tested and everything is fine. Thank you very much !
