### ISSUE TITLE
Visual Studio 2013

### ISSUE THREAD

**Issue by tylorr** [rainers/cv2pdb#9]
Is it possible to compile this with VS 2013? If not, is there a known location where I could get a copy of VS 2010? I couldn't a download link for it anywhere.

**Comment by rainers** [comment]
The solution cv2pdb_vs12.sln is actually made with VS2013. If you don't have Visual D installed, you can ignore the test project.

**Comment by tylorr** [comment]
Great, I got it working. Thanks
